services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./data/mlruns:/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root /mlruns

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: uni-api
    ports:
      - "8000:8000"
    env_file:
      - ./services/api/.env.docker
    volumes:
      - ./data/logs:/app/data/logs
      - ./data/processed:/app/data/processed
      - ./services/api/config:/app/config:ro
      - ./services/api/.env.docker:/app/config/.env.docker:ro
    depends_on:
      - mlflow

  train:
    build: ./services/train
    container_name: uni-train
    env_file:
      - ./services/train/.env.docker
    volumes:
      - ./data/raw_pdfs:/app/data/raw_pdfs
      - ./data/processed:/app/data/processed
      - ./data/logs:/app/data/logs
      - ./services/train/config:/app/config:ro
      - ./services/train/.env.docker:/app/config/.env.docker:ro
    depends_on:
      - mlflow
